### ISSUE TITLE
~ Chapter 5

### ISSUE THREAD

**Issue by leedonggyu1848** [leedonggyu1848/ScalaStudy#1]
# 요약
https://mica-family-a1f.notion.site/basic-970bd3a5853c48eb9df562fa33d0370a
# 문제
https://mica-family-a1f.notion.site/98019262eb5a449e8a2d0cfd468a9088

**Comment by murry2018** [comment]
(노션 페이지 로딩에 시간이 조금 걸립니다)
3, 4, 5장 간단 요약
https://acidic-paprika-8b6.notion.site/3-4-5-3fdbcf73825e47658552959a515bffe7

3, 4, 5장 문제 풀이
https://acidic-paprika-8b6.notion.site/3-4-5-7f5407728f684ffba229bd9d31149210

3, 4, 5장 TMI
https://acidic-paprika-8b6.notion.site/3-4-5-TMI-2d707a71690f42e8b44491639b84f750

PDF 버전
[3_4_5장_간단_요약.pdf](https://github.com/leedonggyu1848/ScalaStudy/files/7109837/3_4_5._._.pdf)
[3_4_5장_연습_문제_풀이.pdf](https://github.com/leedonggyu1848/ScalaStudy/files/7109838/3_4_5._._._.pdf)
[3_4_5장_TMI.pdf](https://github.com/leedonggyu1848/ScalaStudy/files/7110904/3_4_5._TMI.pdf)

**Comment by dlgkdrb2** [comment]
3장 요약 + 문제풀이(방법?)
[scala_3장.pdf](https://github.com/leedonggyu1848/ScalaStudy/files/7111423/scala_3.pdf)

4장 요약 + 문제풀이(방법?)
[scala_4 장.pdf](https://github.com/leedonggyu1848/ScalaStudy/files/7111425/scala_4.pdf)

5장 요약 + 문제풀이(방법?)
[scala_5장.pdf](https://github.com/leedonggyu1848/ScalaStudy/files/7111426/scala_5.pdf)

**Comment by JaeikBae** [comment]
필기 ver
[Scala Study W1.pdf](https://github.com/leedonggyu1848/ScalaStudy/files/7111471/Scala.Study.W1.pdf)

notion ver
https://florentine-newt-fb6.notion.site/Learning-Scala-1-CH-5-770ba65145b1455f801ff0228e098e3e
