### ISSUE TITLE
~ Chapter 7

### ISSUE THREAD

**Issue by leedonggyu1848** [leedonggyu1848/ScalaStudy#3]
**[정리](https://mica-family-a1f.notion.site/collection-547076170a64498a8340a01d33dc018b)**
**[문제](https://mica-family-a1f.notion.site/2-beb5ba5f97324de694b5677ab8c82449)**

**Comment by JaeikBae** [comment]
https://florentine-newt-fb6.notion.site/Learning-Scala-2-CH-7-ca3ec25da0394d1e8e0e2deed9fcab6d

**Comment by dlgkdrb2** [comment]
6장요약
https://dune-clarinet-9db.notion.site/_6-615fc44816124f1097847ddbf1b6e5d4
6장문제
https://dune-clarinet-9db.notion.site/_6-59a7e38f28e4408dad8c105f2fad1e75

7장요약
https://dune-clarinet-9db.notion.site/_7-627990975cb341eb8206ab398b0f7bd9
7장문제
https://dune-clarinet-9db.notion.site/_7-a4c1e8288d754a3a875290e3ba1b1daf

**Comment by murry2018** [comment]
요약
https://acidic-paprika-8b6.notion.site/6-7-790fdbfef96342a294f2c363e4f627e2

문제 풀이
https://acidic-paprika-8b6.notion.site/6-7-6b98394e7106424a80de728403a60712
