### ISSUE TITLE
~Chapter 9

### ISSUE THREAD

**Issue by leedonggyu1848** [leedonggyu1848/ScalaStudy#4]
[정리](https://mica-family-a1f.notion.site/class-fb557de847e04fb982c7030141ff9a03)
[문제](https://mica-family-a1f.notion.site/3-45460ccb5e474108a5065b09bc6951c4)

**Comment by murry2018** [comment]
간단 요약
https://acidic-paprika-8b6.notion.site/8-9-4217e15862974b04b87e5cc448a7448c

문제 풀이(8장밖에 안함)
https://acidic-paprika-8b6.notion.site/8-9-d219c76a77d94da284fb197e95684863

TMI
https://acidic-paprika-8b6.notion.site/8-9-TMI-870e1ca8a2ec4580a02f999e906bb46e

**Comment by JaeikBae** [comment]
https://florentine-newt-fb6.notion.site/Learning-Scala-3-CH-9-5c868b4340fe448fad6a68e13d87466a

**Comment by dlgkdrb2** [comment]
8장 요약
https://dune-clarinet-9db.notion.site/_8-233da99241b54e208072419552b8f1f3

9장 요약
https://dune-clarinet-9db.notion.site/_9-bfaf4d667f954ee1a980a8d201387184

문제는 제가 먹었습니다. 냠냠...
